// i18n translations
export const I18N = {
  uz: {
    appName: "Hamyon",
    hello: "Salom",
    assistant: "Moliyaviy yordamchingiz",
    balance: "Joriy balans",
    todaySummary: "Bugungi xulosa",
    expenses: "Xarajatlar",
    income: "Daromad",
    home: "Bosh",
    stats: "Statistika",
    add: "Qo'shish",
    transactions: "Tranzaksiyalar",
    categories: "Kategoriyalar",
    limits: "Limitlar",
    goals: "Maqsadlar",
    debts: "Qarzlar",
    settings: "Sozlamalar",
    openBot: "Botni ochish",
    addTransaction: "Tranzaksiya qo'shish",
    editTransaction: "Tranzaksiyani tahrirlash",
    type: "Turi",
    expense: "Xarajat",
    incomeType: "Daromad",
    debtType: "Qarz",
    amount: "Summa",
    description: "Tavsif",
    category: "Kategoriya",
    date: "Sana",
    save: "Saqlash",
    cancel: "Bekor",
    delete: "O'chirish",
    edit: "Tahrirlash",
    empty: "Hozircha hech narsa yo'q",
    allTransactions: "Barcha tranzaksiyalar",
    filters: "Filtrlar",
    all: "Hammasi",
    today: "Bugun",
    week: "Bu hafta",
    month: "Bu oy",
    addCategory: "Kategoriya qo'shish",
    editCategory: "Kategoriyani tahrirlash",
    language: "Til",
    dataMode: "Ma'lumotlar rejimi",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Yangilash",
    syncOk: "Synclandi",
    syncFail: "Sync bo'lmadi",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    quickAdd: "Tez qo'shish",
    addExpense: "Xarajat",
    addIncome: "Daromad",
    analytics: "Analitika",
    weekSpending: "Haftalik xarajat",
    monthSpending: "Oylik xarajat",
    topCategories: "Top kategoriyalar",
    noLimits: "Limitlar yo'q",
    noGoals: "Maqsadlar yo'q",
    noCategories: "Kategoriyalar yo'q",
    botHint: "Bot orqali ham qo'shishingiz mumkin",
    tgOpen: "Telegramda ochish",
    resetLocal: "Ma'lumotlarni tozalash",
    deposit: "Qo'shish",
    withdraw: "Olmoq",
    monthlyBudgets: "Oylik byudjetlar",
    spent: "Sarflangan",
    remaining: "Qolgan",
    viewAll: "Hammasini ko'rish",
  },
  ru: {
    appName: "Hamyon",
    hello: "Привет",
    assistant: "Ваш финансовый помощник",
    balance: "Баланс",
    todaySummary: "Сегодня",
    expenses: "Расходы",
    income: "Доходы",
    home: "Главная",
    stats: "Статистика",
    add: "Добавить",
    transactions: "Транзакции",
    categories: "Категории",
    limits: "Лимиты",
    goals: "Цели",
    debts: "Долги",
    settings: "Настройки",
    openBot: "Открыть бота",
    addTransaction: "Добавить транзакцию",
    editTransaction: "Редактировать транзакцию",
    type: "Тип",
    expense: "Расход",
    incomeType: "Доход",
    debtType: "Долг",
    amount: "Сумма",
    description: "Описание",
    category: "Категория",
    date: "Дата",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    empty: "Пока пусто",
    allTransactions: "Все транзакции",
    filters: "Фильтры",
    all: "Все",
    today: "Сегодня",
    week: "Неделя",
    month: "Месяц",
    addCategory: "Добавить категорию",
    editCategory: "Редактировать категорию",
    language: "Язык",
    dataMode: "Режим данных",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Обновить",
    syncOk: "Синхронизировано",
    syncFail: "Ошибка синхронизации",
    confirmDelete: "Удалить?",
    quickAdd: "Быстро добавить",
    addExpense: "Расход",
    addIncome: "Доход",
    analytics: "Аналитика",
    weekSpending: "За неделю",
    monthSpending: "За месяц",
    topCategories: "Топ категории",
    noLimits: "Нет лимитов",
    noGoals: "Нет целей",
    noCategories: "Нет категорий",
    botHint: "Можно добавлять через бота",
    tgOpen: "Открыть в Telegram",
    resetLocal: "Сбросить данные",
    deposit: "Пополнить",
    withdraw: "Снять",
    monthlyBudgets: "Месячные бюджеты",
    spent: "Потрачено",
    remaining: "Осталось",
    viewAll: "Смотреть все",
  },
  en: {
    appName: "Hamyon",
    hello: "Hello",
    assistant: "Your financial assistant",
    balance: "Balance",
    todaySummary: "Today",
    expenses: "Expenses",
    income: "Income",
    home: "Home",
    stats: "Stats",
    add: "Add",
    transactions: "Transactions",
    categories: "Categories",
    limits: "Budgets",
    goals: "Goals",
    debts: "Debts",
    settings: "Settings",
    openBot: "Open bot",
    addTransaction: "Add transaction",
    editTransaction: "Edit transaction",
    type: "Type",
    expense: "Expense",
    incomeType: "Income",
    debtType: "Debt",
    amount: "Amount",
    description: "Description",
    category: "Category",
    date: "Date",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    empty: "Nothing here yet",
    allTransactions: "All transactions",
    filters: "Filters",
    all: "All",
    today: "Today",
    week: "This week",
    month: "This month",
    addCategory: "Add category",
    editCategory: "Edit category",
    language: "Language",
    dataMode: "Data mode",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Sync",
    syncOk: "Synced",
    syncFail: "Sync failed",
    confirmDelete: "Delete?",
    quickAdd: "Quick add",
    addExpense: "Expense",
    addIncome: "Income",
    analytics: "Analytics",
    weekSpending: "Weekly",
    monthSpending: "Monthly",
    topCategories: "Top categories",
    noLimits: "No budgets",
    noGoals: "No goals",
    noCategories: "No categories",
    botHint: "You can add via bot too",
    tgOpen: "Open in Telegram",
    resetLocal: "Reset data",
    deposit: "Deposit",
    withdraw: "Withdraw",
    monthlyBudgets: "Monthly Budgets",
    spent: "Spent",
    remaining: "Remaining",
    viewAll: "View all",
  },
};

export const LANGS = [
  { key: "uz", label: "O'zbek", flag: "🇺🇿" },
  { key: "ru", label: "Русский", flag: "🇷🇺" },
  { key: "en", label: "English", flag: "🇬🇧" },
];

export type LangKey = "uz" | "ru" | "en";
export type Translation = typeof I18N.en;

// Default categories with colors matching Revolut's clean style
export const DEFAULT_CATEGORIES = {
  expense: [
    { id: "food", uz: "Oziq-ovqat", ru: "Продукты", en: "Food", emoji: "🍔", color: "#FF6B6B" },
    { id: "restaurants", uz: "Restoranlar", ru: "Рестораны", en: "Restaurants", emoji: "🍽️", color: "#FF8787" },
    { id: "coffee", uz: "Kofe", ru: "Кофе", en: "Coffee", emoji: "☕", color: "#D4A574" },
    { id: "transport", uz: "Transport", ru: "Транспорт", en: "Transport", emoji: "🚗", color: "#4DABF7" },
    { id: "taxi", uz: "Taksi", ru: "Такси", en: "Taxi", emoji: "🚕", color: "#FFD43B" },
    { id: "fuel", uz: "Benzin", ru: "Бензин", en: "Fuel", emoji: "⛽", color: "#FAB005" },
    { id: "bills", uz: "Kommunal", ru: "Коммунальные", en: "Bills", emoji: "💡", color: "#12B886" },
    { id: "shopping", uz: "Xaridlar", ru: "Покупки", en: "Shopping", emoji: "🛍️", color: "#BE4BDB" },
    { id: "health", uz: "Salomatlik", ru: "Здоровье", en: "Health", emoji: "💊", color: "#F06595" },
    { id: "education", uz: "Ta'lim", ru: "Образование", en: "Education", emoji: "📚", color: "#4DABF7" },
    { id: "entertainment", uz: "Ko'ngilochar", ru: "Развлечения", en: "Fun", emoji: "🎬", color: "#9775FA" },
    { id: "other", uz: "Boshqa", ru: "Другое", en: "Other", emoji: "📦", color: "#868E96" },
  ],
  income: [
    { id: "salary", uz: "Oylik", ru: "Зарплата", en: "Salary", emoji: "💰", color: "#51CF66" },
    { id: "freelance", uz: "Frilanser", ru: "Фриланс", en: "Freelance", emoji: "💻", color: "#40C057" },
    { id: "bonus", uz: "Bonus", ru: "Бонус", en: "Bonus", emoji: "🎉", color: "#F59F00" },
    { id: "other_income", uz: "Boshqa", ru: "Другое", en: "Other", emoji: "💵", color: "#82C91E" },
  ],
  debt: [
    { id: "borrowed", uz: "Qarz oldim", ru: "Взял в долг", en: "Borrowed", emoji: "🤝", color: "#FF6B6B" },
    { id: "lent", uz: "Qarz berdim", ru: "Дал в долг", en: "Lent", emoji: "💸", color: "#51CF66" },
    { id: "loan_payment", uz: "Qarz to'lovi", ru: "Платёж по долгу", en: "Debt payment", emoji: "🏦", color: "#339AF0" },
    { id: "credit", uz: "Kredit karta", ru: "Кредитка", en: "Credit card", emoji: "💳", color: "#845EF7" },
  ],
};

export type CategoryType = "expense" | "income" | "debt";
export type Category = typeof DEFAULT_CATEGORIES.expense[0];
